package barang_temuan;
import koneksi.CampusLostFound;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import index.dashboard;

/**
 *
 * @author icaag
 */
public class lihat_barang_temuan extends javax.swing.JFrame {

    /**
     * Creates new form lihat_barang_temuan
     */
    public lihat_barang_temuan() {
        initComponents();
        loadDataTabel(); // Menampilkan data saat pertama kali dibuka
    }

    // Fungsi untuk memuat data dari database ke tabel UI
        private void loadDataTabel() {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nama Penemu");
            model.addColumn("Nama Barang");
            model.addColumn("Lokasi Temuan");
            model.addColumn("Tanggal");
            model.addColumn("Status");

            try {
                Connection conn = CampusLostFound.koneksiDB();
                String sql = "SELECT * FROM barang_temuan";
                Statement stm = conn.createStatement();
                ResultSet res = stm.executeQuery(sql);

                while (res.next()) {
                    model.addRow(new Object[]{
                        res.getString("nama_penemu"),
                        res.getString("nama_barang"),
                        res.getString("lokasi_temuan"),
                        res.getString("tanggal_temuan"),
                        res.getString("status_pengambilan")
                    });
                }
                jTable1.setModel(model);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
            }
        }

        // Fungsi Pencarian Multi-Indikasi (Global Search)
        private void cariData(String keyword) {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nama Penemu");
            model.addColumn("Nama Barang");
            model.addColumn("Lokasi Temuan");
            model.addColumn("Tanggal");
            model.addColumn("Status");

            try {
                Connection conn = CampusLostFound.koneksiDB();
                // Mencari kecocokan kata di semua kolom teks utama
                String sql = "SELECT * FROM barang_temuan WHERE nama_penemu LIKE ? "
                           + "OR nama_barang LIKE ? OR lokasi_temuan LIKE ? OR status_pengambilan LIKE ?";

                PreparedStatement pst = conn.prepareStatement(sql);
                String queryKeyword = "%" + keyword + "%";
                pst.setString(1, queryKeyword);
                pst.setString(2, queryKeyword);
                pst.setString(3, queryKeyword);
                pst.setString(4, queryKeyword);

                ResultSet res = pst.executeQuery();
                while (res.next()) {
                    model.addRow(new Object[]{
                        res.getString("nama_penemu"),
                        res.getString("nama_barang"),
                        res.getString("lokasi_temuan"),
                        res.getString("tanggal_temuan"),
                        res.getString("status_pengambilan")
                    });
                }
                jTable1.setModel(model);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pencarian Gagal: " + e.getMessage());
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 249, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Barang Temuan");

        jLabel2.setText("Cari Barang Temuan");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        backbutton.setText("Kembali");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backbutton)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(488, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(442, 442, 442))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(backbutton))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris >= 0) {
            // Ambil data lama sebagai acuan WHERE clause agar tidak salah update data orang lain
            String lamaPenemu = jTable1.getValueAt(baris, 0).toString();
            String lamaBarang = jTable1.getValueAt(baris, 1).toString();
            String lamaLokasi = jTable1.getValueAt(baris, 2).toString();
            String lamaTanggal = jTable1.getValueAt(baris, 3).toString();
            String lamaStatus = jTable1.getValueAt(baris, 4).toString();

            // Pilihan aksi untuk user
            Object[] options = {"Simpan Perubahan (Edit)", "Hapus Baris Ini", "Batal"};
            int n = JOptionPane.showOptionDialog(this,
                "Pilih tindakan untuk data milik: " + lamaPenemu,
                "Kelola Data Barang Temuan",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[2]);

            if (n == JOptionPane.YES_OPTION) {
                // --- PROSES EDIT (Bisa edit semua field termasuk nama) ---
                String baruPenemu = JOptionPane.showInputDialog(this, "Ubah Nama Penemu:", lamaPenemu);
                if (baruPenemu == null) return; 
                
                String baruBarang = JOptionPane.showInputDialog(this, "Ubah Nama Barang:", lamaBarang);
                if (baruBarang == null) return;
                
                String baruLokasi = JOptionPane.showInputDialog(this, "Ubah Lokasi Temuan:", lamaLokasi);
                if (baruLokasi == null) return;
                
                String baruTanggal = JOptionPane.showInputDialog(this, "Ubah Tanggal (YYYY-MM-DD):", lamaTanggal);
                if (baruTanggal == null) return;

                String baruStatus = JOptionPane.showInputDialog(this, "Ubah Status Pengembalian:", lamaStatus);
                if (baruStatus == null) return;

                try {
                    Connection conn = CampusLostFound.koneksiDB();
                    // Menggunakan semua parameter data lama di WHERE clause sebagai pengganti ID
                    String sql = "UPDATE barang_temuan SET nama_penemu=?, nama_barang=?, lokasi_temuan=?, tanggal_temuan=?, status_pengambilan=? "
                               + "WHERE nama_penemu=? AND nama_barang=? AND lokasi_temuan=? AND tanggal_temuan=? AND status_pengambilan=?";
                    
                    PreparedStatement pst = conn.prepareStatement(sql);
                    // Data Baru (SET)
                    pst.setString(1, baruPenemu);
                    pst.setString(2, baruBarang);
                    pst.setString(3, baruLokasi);
                    pst.setString(4, baruTanggal);
                    pst.setString(5, baruStatus);
                    // Data Lama (WHERE)
                    pst.setString(6, lamaPenemu);
                    pst.setString(7, lamaBarang);
                    pst.setString(8, lamaLokasi);
                    pst.setString(9, lamaTanggal);
                    pst.setString(10, lamaStatus);

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diedit!");
                    loadDataTabel(); // Refresh tabel
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal Edit: " + e.getMessage());
                }

            } else if (n == JOptionPane.NO_OPTION) {
                // --- PROSES HAPUS ---
                int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
                if (konfirmasi == JOptionPane.YES_OPTION) {
                    try {
                        Connection conn = CampusLostFound.koneksiDB();
                        String sql = "DELETE FROM barang_temuan WHERE nama_penemu=? AND nama_barang=? AND lokasi_temuan=? AND tanggal_temuan=? AND status_pengambilan=?";
                        PreparedStatement pst = conn.prepareStatement(sql);
                        pst.setString(1, lamaPenemu);
                        pst.setString(2, lamaBarang);
                        pst.setString(3, lamaLokasi);
                        pst.setString(4, lamaTanggal);
                        pst.setString(5, lamaStatus);
                        
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                        loadDataTabel(); // Refresh tabel
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        index.dashboard halamanDashboard = new index.dashboard();
        halamanDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihat_barang_temuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihat_barang_temuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihat_barang_temuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihat_barang_temuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihat_barang_temuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
