/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barang_temuan;
import index.dashboard;

import koneksi.CampusLostFound;

/**
 *
 * @author nanaz
 */
public class penemu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(penemu.class.getName());

    /**
     * Creates new form penemu
     */
    public penemu() {
        initComponents();
        loadDataTabel();
        cbStatus.removeAllItems();
        cbStatus.addItem("Pilih Status...");
        cbStatus.addItem("Belum Diambil");
        cbStatus.addItem("Sudah Dikembalikan");
        cbStatus.addItem("Dititipkan di Satpam");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 249, 255));

        jLabel1.setText("Nama Penemu");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        jLabel2.setText("Nama Barang");

        txtNamaBarang.addActionListener(this::txtNamaBarangActionPerformed);

        jLabel3.setText("Lokasi Ditemukan");

        txtLokasi.addActionListener(this::txtLokasiActionPerformed);

        jLabel4.setText("Tanggal Ditemukan");

        jLabel5.setText("Status Pengembalian");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbStatus.addActionListener(this::cbStatusActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        backbutton.setText("Kembali");
        backbutton.addActionListener(this::backbuttonActionPerformed);

        jButton3.setText("Edit");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton2.setText("Hapus");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton1.setText("Simpan");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("INFORMASI PENEMU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6)
                        .addGap(284, 284, 284)
                        .addComponent(backbutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLokasi)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbutton)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            // Panggil koneksi database
            java.sql.Connection kon = CampusLostFound.koneksiDB();
            
            // Query harus sesuai urutan: nama_penemu, nama_barang, lokasi_temuan, tanggal_temuan, status_pengambilan
            String sql = "INSERT INTO barang_temuan (nama_penemu, nama_barang, lokasi_temuan, tanggal_temuan, status_pengambilan) VALUES (?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pst = kon.prepareStatement(sql);
            
            // 1. Nama Penemu
            pst.setString(1, txtNama.getText());
            // 2. Nama Barang
            pst.setString(2, txtNamaBarang.getText());
            // 3. Lokasi Ditemukan
            pst.setString(3, txtLokasi.getText());
            
            // 4. Tanggal Ditemukan
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tgl = "";
            if (jDateChooser1.getDate() != null) {
                tgl = sdf.format(jDateChooser1.getDate());
            }
            pst.setString(4, tgl);
            
            // 5. Status Pengambilan
            pst.setString(5, cbStatus.getSelectedItem().toString());
            
            // Validasi: Pastikan user sudah memilih status (bukan "Pilih Status...")
            if (cbStatus.getSelectedIndex() == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Tolong pilih status pengembalian terlebih dahulu!");
                return;
            }
            
            // Eksekusi query
            pst.execute();
            javax.swing.JOptionPane.showMessageDialog(null, "Laporan barang temuan berhasil disimpan!");
            
            // Refresh tabel
            loadDataTabel();
            
            // Bersihkan kotak isian
            txtNama.setText("");
            txtNamaBarang.setText("");
            txtLokasi.setText("");
            jDateChooser1.setDate(null);
            cbStatus.setSelectedIndex(0); 
            
        } catch (java.awt.HeadlessException | java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
  int baris = jTable1.rowAtPoint(evt.getPoint());
        
        if (baris >= 0) {
            // Menarik data dari tabel ke kotak isian
            txtNama.setText(jTable1.getValueAt(baris, 0) != null ? jTable1.getValueAt(baris, 0).toString() : "");
            txtNamaBarang.setText(jTable1.getValueAt(baris, 1) != null ? jTable1.getValueAt(baris, 1).toString() : "");
            txtLokasi.setText(jTable1.getValueAt(baris, 2) != null ? jTable1.getValueAt(baris, 2).toString() : "");
            
            try {
                String tanggalTabel = jTable1.getValueAt(baris, 3).toString(); 
                java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggalTabel);
                jDateChooser1.setDate(date);
            } catch (Exception e) {
                jDateChooser1.setDate(null);
                
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
            java.sql.Connection conn = CampusLostFound.koneksiDB(); 
            
            // Perhatikan urutan SET-nya: barang, lokasi, tanggal, status. 
            // WHERE-nya berdasarkan nama_penemu.
            String sql = "UPDATE barang_temuan SET nama_barang = ?, lokasi_temuan = ?, tanggal_temuan = ?, status_pengambilan = ? WHERE nama_penemu = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            // Format Tanggal
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tgl = "";
            if (jDateChooser1.getDate() != null) {
                tgl = sdf.format(jDateChooser1.getDate());
            }
            
            // 1. Nama Barang
            pst.setString(1, txtNamaBarang.getText());
            // 2. Lokasi Temuan
            pst.setString(2, txtLokasi.getText());
            // 3. Tanggal Temuan
            pst.setString(3, tgl); 
            // 4. Status Pengambilan
            pst.setString(4, cbStatus.getSelectedItem().toString());
            // 5. Patokan (Nama Penemu)
            pst.setString(5, txtNama.getText());
            
            int teredit = pst.executeUpdate(); 
            
            if (teredit > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
                loadDataTabel();  
                txtNama.setText("");     
                txtNamaBarang.setText("");
                txtLokasi.setText("");
                jDateChooser1.setDate(null);
                cbStatus.setSelectedIndex(0); // Reset ke "Pilih Status..."
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal Edit! Pastikan Anda mengklik baris di tabel terlebih dahulu.");
            }
            
        } catch (java.awt.HeadlessException | java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int dialogBtn = javax.swing.JOptionPane.YES_NO_OPTION;
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data temuan ini?", "Peringatan", dialogBtn);    
        
        if (dialogResult == 0) {
            try {
                java.sql.Connection conn = CampusLostFound.koneksiDB(); 
                if (cbStatus.getSelectedIndex() == 0) {
    javax.swing.JOptionPane.showMessageDialog(null, "Tolong pilih status pengembalian terlebih dahulu!");
    return; // Berhenti di sini, tidak lanjut ke proses database
}
                
                String sql = "DELETE FROM barang_temuan WHERE nama_penemu = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtNama.getText());
                
                int terhapus = pst.executeUpdate(); 
                
                if (terhapus > 0) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    loadDataTabel(); 
                    txtNama.setText("");     
                    txtNamaBarang.setText("");
                    txtLokasi.setText("");
cbStatus.setSelectedIndex(0);                    jDateChooser1.setDate(null);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Gagal! Data dengan nama tersebut tidak ditemukan di database.");
                }
                
            } catch (java.awt.HeadlessException | java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error Hapus: " + e.getMessage());
            }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        index.dashboard halamanDashboard = new index.dashboard();
        halamanDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new penemu().setVisible(true));
    }
    private void loadDataTabel() {
        // Membuat judul kolom pada tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Nama Penemu");
        model.addColumn("Nama Barang");
        model.addColumn("Lokasi Temuan");
        model.addColumn("Tanggal");
        model.addColumn("Status");

        try {
            // Memanggil koneksi database
            java.sql.Connection conn = CampusLostFound.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            
            // Mengambil semua data dari tabel barang_temuan
            java.sql.ResultSet res = stm.executeQuery("SELECT * FROM barang_temuan");

            // Memasukkan data dari database ke dalam baris tabel UI
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("nama_penemu"),
                    res.getString("nama_barang"),
                    res.getString("lokasi_temuan"),
                    res.getString("tanggal_temuan"),
                    res.getString("status_pengambilan")
                });
            }
            
            // Set model ke JTable
            jTable1.setModel(model);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data tabel: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}
