package User;
import koneksi.CampusLostFound;
import koneksi.CampusLostFound;
import koneksi.CampusLostFound;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import index.dashboard;

/**
 *
 * @author icaag
 */
public class lihat_user extends javax.swing.JFrame {
    Connection conn;

    /**
     * Creates new form lihat_user
     */
    public lihat_user() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        tampilData(""); // Memuat data pertama kali tanpa filter pencarian
    }
    
private void tampilData(String keyword) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        model.addColumn("Nama");
        model.addColumn("NIM");
        model.addColumn("Email");
        model.addColumn("No HP");
        
        try {
            conn = CampusLostFound.koneksiDB();
            String sql;
            
            // Perbaikan Query: Sekarang support pencarian Nama, NIM, Email, dan No HP sekaligus
            if (keyword.equals("")) {
                sql = "SELECT * FROM user";
            } else {
                sql = "SELECT * FROM user WHERE nama LIKE '%" + keyword + "%' "
                    + "OR nim LIKE '%" + keyword + "%' "
                    + "OR email LIKE '%" + keyword + "%' "
                    + "OR no_hp LIKE '%" + keyword + "%'";
            }
            
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("nama"),
                    res.getString("nim"),
                    res.getString("email"),
                    res.getString("no_hp")
                });
            }
            // Sesuai nama variabel komponen kamu di NetBeans
            jTable1.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(245, 249, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("DATA USER");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Cari user :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backbutton.setText("Kembali");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(521, 521, 521)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 590, Short.MAX_VALUE)
                        .addComponent(backbutton)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(backbutton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField1.getText();
        tampilData(keyword);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField1.getText();
        tampilData(keyword);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris == -1) return;

        // Ambil data string dari baris yang diklik untuk modal input / pencarian target
        String namaLama = jTable1.getValueAt(baris, 0).toString();
        String nimLama  = jTable1.getValueAt(baris, 1).toString();
        String emailLama = jTable1.getValueAt(baris, 2).toString();
        String noHpLama  = jTable1.getValueAt(baris, 3).toString();

        // Menyediakan opsi tindakan kepada user dalam bentuk tombol pop-up dialog
        Object[] opsiMenu = {"Edit Data", "Hapus Data", "Batal"};
        int pilihan = JOptionPane.showOptionDialog(this, 
                "Pilih aksi untuk data user: " + namaLama, 
                "Opsi Pintasan Data", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.QUESTION_MESSAGE, 
                null, opsiMenu, opsiMenu[0]);

        // JIKA USER MEMILIH: EDIT DATA
        // JIKA USER MEMILIH: EDIT DATA
        if (pilihan == 0) {
            // 1. Munculkan pop-up input berturut-turut untuk semua data
            String namaBaru = JOptionPane.showInputDialog(this, "Ubah Nama:", namaLama);
            if (namaBaru == null || namaBaru.trim().equals("")) return; 
            
            String nimBaru = JOptionPane.showInputDialog(this, "Ubah NIM:", nimLama);
            if (nimBaru == null || nimBaru.trim().equals("")) return;
            
            String emailBaru = JOptionPane.showInputDialog(this, "Ubah Email:", emailLama);
            if (emailBaru == null || emailBaru.trim().equals("")) return;
            
            String noHpBaru = JOptionPane.showInputDialog(this, "Ubah No HP:", noHpLama);
            if (noHpBaru == null || noHpBaru.trim().equals("")) return;

            try {
                conn = CampusLostFound.koneksiDB();
                
                // 2. Ambil id_user asli dari database berdasarkan NIM sebelum diedit
                String sqlGetId = "SELECT id_user FROM user WHERE nim=?";
                PreparedStatement pstId = conn.prepareStatement(sqlGetId);
                pstId.setString(1, nimLama);
                ResultSet rsId = pstId.executeQuery();
                
                if (rsId.next()) {
                    String idTarget = rsId.getString("id_user");
                    
                    // 3. Query UPDATE diubah agar memperbarui SEMUA KOLOM sekaligus
                    String sqlUpdate = "UPDATE user SET nama=?, nim=?, email=?, no_hp=? WHERE id_user=?";
                    PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                    pstUpdate.setString(1, namaBaru);
                    pstUpdate.setString(2, nimBaru);
                    pstUpdate.setString(3, emailBaru);
                    pstUpdate.setString(4, noHpBaru);
                    pstUpdate.setString(5, idTarget); // id_user sebagai kunci target
                    
                    pstUpdate.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Semua data berhasil diperbarui!");
                    tampilData(""); // Refresh isi tabel
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal mengedit data: " + e.getMessage());
            }

        // JIKA USER MEMILIH: HAPUS DATA
        } else if (pilihan == 1) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                    "Yakin ingin menghapus data " + namaLama + "?", 
                    "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    conn = CampusLostFound.koneksiDB();
                    
                    // Cari id_user asli di database berdasarkan NIM lama yang diklik
                    String sqlGetId = "SELECT id_user FROM user WHERE nim=?";
                    PreparedStatement pstId = conn.prepareStatement(sqlGetId);
                    pstId.setString(1, nimLama);
                    ResultSet rsId = pstId.executeQuery();
                    
                    if (rsId.next()) {
                        String idTarget = rsId.getString("id_user");
                        
                        // Jalankan query DELETE berdasarkan id_user target
                        String sqlDelete = "DELETE FROM user WHERE id_user=?";
                        PreparedStatement pstDelete = conn.prepareStatement(sqlDelete);
                        pstDelete.setString(1, idTarget);
                        
                        pstDelete.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                        tampilData(""); // Refresh isi tabel
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        index.dashboard halamanDashboard = new index.dashboard();
        halamanDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihat_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihat_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihat_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihat_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihat_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
