

package barang_hilang;

import koneksi.CampusLostFound;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import index.dashboard;

/**
 *
 * @author nanaz
 */
public class TambahLaporanForm extends javax.swing.JFrame {
    

    /**
     * Creates new form TambahLaporanForm
     */
    public TambahLaporanForm() {
        initComponents();
        loadDataTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 249, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Laporan Barang Hilang");

        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Nama  Pelapor");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Nama Barang");

        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Lokasi hilang");

        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Tanggal");

        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Deskripsi Barang");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsi);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID User", "Nama Barang", "Lokasi Hilang", "Tanggal", "Deskripsi baranf"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Simpan Laporan");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Edit");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton2.setText("Hapus");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        backbutton.setText("Kembali");
        backbutton.addActionListener(this::backbuttonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtNama))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtLokasi)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaBarang)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 376, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(294, 294, 294)
                                .addComponent(backbutton)))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
  // Panggil koneksi database
    java.sql.Connection kon;
    kon = CampusLostFound.koneksiDB();
    
    // Siapkan query INSERT
    String sql = "INSERT INTO barang_hilang (nama_pelapor, nama_barang, lokasi_hilang, tanggal_hilang, deskripsi) VALUES (?, ?, ?, ?, ?)";
    java.sql.PreparedStatement pst = kon.prepareStatement(sql);
    
    // Ambil data dari kolom isian UI (TextField)
    pst.setString(1, txtNama.getText());
    pst.setString(2, txtNamaBarang.getText());
    pst.setString(3, txtLokasi.getText());
    
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tgl = "";
            if (jDateChooser1.getDate() != null) {
                tgl = sdf.format(jDateChooser1.getDate());
            }
    pst.setString(4, tgl);
pst.setString(5, txtDeskripsi.getText());
    
    // Eksekusi query
    pst.execute();
    
    // Tampilkan pesan sukses
    javax.swing.JOptionPane.showMessageDialog(null, "Laporan berhasil disimpan!");
    loadDataTabel();
    // Tutup form input ini setelah berhasil
    
    
} catch (HeadlessException | SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
int baris = jTable1.rowAtPoint(evt.getPoint());
        
        if (baris >= 0) {
            // Ini kode yang memaksa tulisan di tabel pindah ke kotak isian atas
            txtNama.setText(jTable1.getValueAt(baris, 0) != null ? jTable1.getValueAt(baris, 0).toString() : "");
            txtNamaBarang.setText(jTable1.getValueAt(baris, 1) != null ? jTable1.getValueAt(baris, 1).toString() : "");
            txtLokasi.setText(jTable1.getValueAt(baris, 2) != null ? jTable1.getValueAt(baris, 2).toString() : "");
            
            try {
                String tanggalTabel = jTable1.getValueAt(baris, 3).toString(); 
                java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggalTabel);
                jDateChooser1.setDate(date);
            } catch (Exception e) {
                jDateChooser1.setDate(null);
            }
            
            txtDeskripsi.setText(jTable1.getValueAt(baris, 4) != null ? jTable1.getValueAt(baris, 4).toString() : "");
        }
    }//GEN-LAST:event_formMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int dialogBtn = javax.swing.JOptionPane.YES_NO_OPTION;
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Peringatan", dialogBtn);    
        
        if (dialogResult == 0) {
            try {
                java.sql.Connection conn = CampusLostFound.koneksiDB(); 
                
                String sql = "DELETE FROM barang_hilang WHERE nama_pelapor = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtNama.getText());
                
                int terhapus = pst.executeUpdate(); // Mengecek apakah ada baris yang terhapus
                
                if (terhapus > 0) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    loadDataTabel(); 
                    
                    txtNama.setText("");     
                    txtNamaBarang.setText("");
                    txtLokasi.setText("");
                    txtDeskripsi.setText("");
                    jDateChooser1.setDate(null);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Gagal! Data dengan nama tersebut tidak ditemukan di database.");
                }
                
            } catch (HeadlessException | SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            java.sql.Connection conn = CampusLostFound.koneksiDB(); 
            
            String sql = "UPDATE barang_hilang SET nama_barang = ?, lokasi_hilang = ?, tanggal_hilang = ?, deskripsi = ? WHERE nama_pelapor = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tgl = "";
            if (jDateChooser1.getDate() != null) {
                tgl = sdf.format(jDateChooser1.getDate());
            }
            
            pst.setString(1, txtNamaBarang.getText());
            pst.setString(2, txtLokasi.getText());
            pst.setString(3, tgl); 
            pst.setString(4, txtDeskripsi.getText());
            pst.setString(5, txtNama.getText()); 
            
            int teredit = pst.executeUpdate(); // Mengecek apakah ada baris yang terupdate
            
            if (teredit > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
                loadDataTabel();  
                
                txtNama.setText("");     
                txtNamaBarang.setText("");
                txtLokasi.setText("");
                txtDeskripsi.setText("");
                jDateChooser1.setDate(null);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal Edit! Pastikan Anda mengklik baris di tabel terlebih dahulu.");
            }
            
        } catch (HeadlessException | SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int baris = jTable1.rowAtPoint(evt.getPoint());
        
        if (baris >= 0) {
            // Menarik data dari tabel ke kotak isian
            txtNama.setText(jTable1.getValueAt(baris, 0) != null ? jTable1.getValueAt(baris, 0).toString() : "");
            txtNamaBarang.setText(jTable1.getValueAt(baris, 1) != null ? jTable1.getValueAt(baris, 1).toString() : "");
            txtLokasi.setText(jTable1.getValueAt(baris, 2) != null ? jTable1.getValueAt(baris, 2).toString() : "");
            
            try {
                String tanggalTabel = jTable1.getValueAt(baris, 3).toString(); 
                java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggalTabel);
                jDateChooser1.setDate(date);
            } catch (ParseException e) {
                jDateChooser1.setDate(null);
            }
            
            txtDeskripsi.setText(jTable1.getValueAt(baris, 4) != null ? jTable1.getValueAt(baris, 4).toString() : "");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        index.dashboard halamanDashboard = new index.dashboard();
        halamanDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed
public static void main(String args[]) {

    try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(() -> {
        new TambahLaporanForm().setVisible(true);
    });
}
   
    
    
private void loadDataTabel() {
        // Membuat judul kolom pada tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Nama Pelapor");
        model.addColumn("Nama Barang");
        model.addColumn("Lokasi Hilang");
        model.addColumn("Tanggal");
        model.addColumn("Deskripsi");

        try {
            // Memanggil koneksi database
            java.sql.Connection conn = CampusLostFound.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            
            // Mengambil semua data dari tabel barang_hilang
            java.sql.ResultSet res = stm.executeQuery("SELECT * FROM barang_hilang");

            // Memasukkan data dari database ke dalam baris tabel UI
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("nama_pelapor"),
                    res.getString("nama_barang"),
                    res.getString("lokasi_hilang"),
                    res.getString("tanggal_hilang"),
                    res.getString("deskripsi")
                });
            }
            
            // Set model ke JTable
            jTable1.setModel(model);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data tabel: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}